sudo: required
dist: trusty
language: generic
compiler:
  - gcc
  - clang

env:
  matrix:
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - export TARGET_REPO_PATH=$(pwd)
  - export TARGET_REPO_NAME=${PWD##*/}
  - mkdir -p ~/ros/ws_$TARGET_REPO_NAME/src
  - wstool init
  - curl https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/rtt_lwr.rosinstall | wstool merge -k -
  - curl https://raw.githubusercontent.com/kuka-isir/rtt_lwr/rtt_lwr-2.0/lwr_utils/config/rtt_lwr_extras.rosinstall | wstool merge -k -
  - curl https://raw.githubusercontent.com/IDSCETHZurich/re_trajectory-generator/master/kuka_IK/include/friComm.h >> ~/ros/ws_$TARGET_REPO_NAME/src/rtt_lwr/lwr_hardware/kuka_lwr_fri/include/kuka_lwr_fri/friComm.h
  - wstool update -j2 --continue-on-error
 script:
  - source .ci_config/travis.sh

