sudo: required
dist: trusty
language: generic
compiler:
  - gcc
  - clang

env:
  matrix:
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="jade"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - NOT_TEST_BUILD=true USE_DEB=true  UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=rtt_lwr_controllers ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
 script:
  - source .ci_config/travis.sh

